version: 2

sources:
  - name: raw
    schema: gz_raw_data
    #loaded_at_field: "CAST(date_date AS TIMESTAMP)"
    #freshness:
      #warn_after:
        #count: 90
        #period: day
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: >
          sales of Greenweez / we have one row per product_id 
          found in each orders_id
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: "Composite key for uniqueness test"
            tests:
              - unique
              - not_null
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity

      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
      - name: raw_adwords
        identifier:  raw_gz_adwords
      - name: raw_bing
        identifier:  raw_gz_bing
      - name: raw_criteo
        identifier:  raw_gz_criteo
      - name: raw_facebook
        identifier:  raw_gz_facebook
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
models:
  # ==========================================
  # INTERMEDIATE MODELS
  # ==========================================

  - name: int_orders_margin
    description: "Margin calculation aggregated per order."
    columns:
      - name: orders_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: margin
        description: "Margin = revenue - purchase_cost"
        tests:
          - not_null
      - name: Purchase_cost
        description: "Purchase_cost = quantity * purchase_price"
        tests:
          - not_null
      - name: date_date
        description: "Date of the order"
        tests:
          - not_null
      - name: revenue
        description: "Sum of revenue per order"
        tests:
          - not_null
      - name: quantity
        description: "Sum of quantity per order"
        tests:
          - not_null

  - name: int_sales_margin
    description: "Margin calculation per order line / product sales."
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
    columns:
      - name: orders_id
        description: "Orders key"
        tests:
          - not_null
      - name: products_id
        description: "Products key"
        tests:
          - not_null
      - name: margin
        description: "Margin = revenue - purchase_cost"
        tests:
          - not_null
      - name: Purchase_cost
        description: "Purchase_cost = quantity * purchase_price"
        tests:
          - not_null
      - name: date_date
        description: "Date of the order"
        tests:
          - not_null
      - name: revenue
        description: "Sum of revenue per order"
        tests:
          - not_null
      - name: quantity
        description: "Sum of quantity per order"
        tests:
          - not_null

  - name: int_orders_operational
    description: "Operational margin calculation per order (including logistics and shipping)."
    columns:
      - name: orders_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: date_date
        description: "Date of the order"
        tests:
          - not_null
      - name: operational_margin
        description: "operational_margin = margin + shipping_fee - log_cost - ship_cost"
      - name: quantity
        description: "Sum of quantity per order"
        tests:
          - not_null
      - name: revenue
        description: "Sum of revenue per order"
        tests:
          - not_null
      - name: purchase_cost
        description: "Purchase_cost = quantity * purchase_price"
        tests:
          - not_null
      - name: margin
        description: "Margin = revenue - purchase_cost"
        tests:
          - not_null
      - name: shipping_fee
        description: "The price the customer pays for shipping"
      - name: log_cost
        description: "The cost of preparing the parcel in the warehouse"
      - name: ship_cost
        description: "Shipping cost paid by the company to the carrier"